### ISSUE TITLE
Add functionality for vars to be used in workflow reference

### ISSUE THREAD

**Issue by Wade9320** [actions/reusable-workflows#12]
It would be great if there was functionality when using a reusable workflow instead of supplying the branch name or tag name but instead using an environment variable. 

The advantage of this is that it would allow teams to version their templates, and also rollback the usage of template much quicker.
GitLab supports this functionality through their templates.

Below is an example of what it would look like

```yml
jobs:
  tflint-tf:
    uses: example-org/github-actions-templates/.github/workflows/terraform-lint.yml@${{ vars.TEMPLATE_VERSION }}
```

This var would be set at an Organisation level.
